

DROP TABLE "TBL_VOTE";
DROP TABLE "TBL_GRADE";
DROP TABLE "TBL_MEMBER";
DROP TABLE "TBL_PARTY";

CREATE TABLE "TBL_PARTY" (
	"PCODE"	CHAR(2)		NOT NULL,
	"PNAME"	VARCHAR2(20)		NULL,
	"PINDATE"	DATE		NULL,
	"PLEADER"	VARCHAR2(20)		NULL,
	"PTEL1"	CHAR(3)		NULL,
	"PTEL2"	CHAR(4)		NULL,
	"PTEL3"	CHAR(4)		NULL
);
COMMENT ON COLUMN "TBL_PARTY"."PCODE" IS '정당';
COMMENT ON COLUMN "TBL_PARTY"."PNAME" IS '명칭';
COMMENT ON COLUMN "TBL_PARTY"."PINDATE" IS '등록년월일';
COMMENT ON COLUMN "TBL_PARTY"."PLEADER" IS '대표자';
COMMENT ON COLUMN "TBL_PARTY"."PTEL1" IS '전화번호1';
COMMENT ON COLUMN "TBL_PARTY"."PTEL2" IS '전화번호2';
COMMENT ON COLUMN "TBL_PARTY"."PTEL3" IS '전화번호3';


CREATE TABLE "TBL_MEMBER" (
	"MNO"	CHAR(1)		NOT NULL,
	"MNAME"	VARCHAR2(20)		NULL,
	"MJUMIN"	CHAR(13)		NULL,
	"PSCHOOL"	CHAR(1)		NULL,
	"MCITY"	VARCHAR2(20)		NULL,
	"PCODE"	CHAR(2)		NOT NULL
);
COMMENT ON COLUMN "TBL_MEMBER"."MNO" IS '후보';
COMMENT ON COLUMN "TBL_MEMBER"."MNAME" IS '성명';
COMMENT ON COLUMN "TBL_MEMBER"."MJUMIN" IS '후보자';
COMMENT ON COLUMN "TBL_MEMBER"."PSCHOOL" IS '최종학력';
COMMENT ON COLUMN "TBL_MEMBER"."MCITY" IS '지역구';
COMMENT ON COLUMN "TBL_MEMBER"."PCODE" IS '소속';


CREATE TABLE "TBL_GRADE" (
	"MNO"	CHAR(1)		NOT NULL,
	"GDATE"	DATE		NULL,
	"GSCHOOL_NAME"	VARCHAR2(20)		NULL
);
COMMENT ON COLUMN "TBL_GRADE"."MNO" IS '후보';
COMMENT ON COLUMN "TBL_GRADE"."GDATE" IS '졸업년월일';
COMMENT ON COLUMN "TBL_GRADE"."GSCHOOL_NAME" IS '졸업학교명';


CREATE TABLE "TBL_VOTE" (
	"VJUMIN"	CHAR(13)		NOT NULL,
	"VNAME"	VARCHAR2(20)		NULL,
	"VTIME"	CHAR(4)		NULL,
	"VAREA"	CHAR(20)		NULL,
	"VCONFIRM"	CHAR(1)		NULL,
	"MNO"	CHAR(1)		NOT NULL
);
COMMENT ON COLUMN "TBL_VOTE"."VJUMIN" IS '투표자';
COMMENT ON COLUMN "TBL_VOTE"."VNAME" IS '성명';
COMMENT ON COLUMN "TBL_VOTE"."VTIME" IS '투표시간';
COMMENT ON COLUMN "TBL_VOTE"."VAREA" IS '투표장소';
COMMENT ON COLUMN "TBL_VOTE"."VCONFIRM" IS '유권자';
COMMENT ON COLUMN "TBL_VOTE"."MNO" IS '후보';



ALTER TABLE "TBL_PARTY" ADD CONSTRAINT "PK_TBL_PARTY" PRIMARY KEY (
	"PCODE"
);

ALTER TABLE "TBL_MEMBER" ADD CONSTRAINT "PK_TBL_MEMBER" PRIMARY KEY (
	"MNO"
);

ALTER TABLE "TBL_VOTE" ADD CONSTRAINT "PK_TBL_VOTE" PRIMARY KEY (
	"VJUMIN"
);

ALTER TABLE "TBL_GRADE" ADD CONSTRAINT "PK_TBL_GRADE" PRIMARY KEY (
	"MNO"
);

ALTER TABLE "TBL_MEMBER" ADD CONSTRAINT "FK_TBL_PARTY_TO_TBL_MEMBER_1" FOREIGN KEY (
	"PCODE"
)
REFERENCES "TBL_PARTY" (
	"PCODE"
);

ALTER TABLE "TBL_VOTE" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_VOTE_1" FOREIGN KEY (
	"MNO"
)
REFERENCES "TBL_MEMBER" (
	"MNO"
);

ALTER TABLE "TBL_GRADE" ADD CONSTRAINT "FK_TBL_MEMBER_TO_TBL_GRADE_1" FOREIGN KEY (
	"MNO"
)
REFERENCES "TBL_MEMBER" (
	"MNO"
);
